admin_platform_role:
    resource: |
        alias: sylius.role
        section: admin
        path: roles
        templates: PlatformAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: admin_platform_role
        permission: true
        form:
            options:
                validation_groups: [platform_admin]
        vars:
            all:
                subheader: sylius.ui.manage_user_roles
                templates:
                    form: PlatformAdminBundle:Role:_form.html.twig
            index:
                icon: lock
    type: sylius.resource
